[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Proton <feisuzhu@163.com>"]

[tool.poetry.dependencies]
python = "^3.10"
redis = "^4.3.5"
requests = "^2.28.1"
raven = "^6.10.0"
gunicorn = "^20.1.0"
django = "^4.1.7"
graphene = "^3.2.2"
django-annoying = "^0.10.6"
graphene-django = "^3.0.0"
django-redis-sessions = "^0.6.2"
itsdangerous = "^2.1.2"
msgpack = "^1.0.4"
pymysql = "^1.0.2"
psycopg2-binary = "^2.9.5"
pyyaml = "^6.0"
django-schema-graph = "^2.2.1"
trueskill = "^0.4.5"
qrcode = {extras = ["pil"], version = "^7.3.1"}
Pillow = "^9.2.0"
sentry-sdk = "^1.7.1"

[[tool.poetry.source]]
name = "tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple"


[tool.poetry.group.dev.dependencies]
neovim = "^0.3.1"
jedi = "^0.18.2"
flake8 = "^6.0.0"
werkzeug = "^2.2.2"
pprintpp = "^0.4.0"
ipython = "^8.7.0"
django-debug-permissions = "^1.0.0"
pytest-django = "^4.5.2"
factory-boy = "^3.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
